<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>6. Exploring virtual species</title>

<script src="site_libs/header-attrs-2.25/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/yeti.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Virtualspecies tutorial</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Introduction</a>
</li>
<li>
  <a href="01-inputdata.html">1. Input data</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Simulating virtual species
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="02-response.html">2. Virtual species defined by response to environmental variables</a>
    </li>
    <li>
      <a href="03-PCA.html">3. Virtual species defined by response to a PCA of the environment</a>
    </li>
    <li>
      <a href="04-presenceabsence.html">4. Converting environmental suitability to presence-absence</a>
    </li>
    <li>
      <a href="05-randomspecies.html">5. Generating random species</a>
    </li>
  </ul>
</li>
<li>
  <a href="06-virtualspeciesobjects.html">6. Exploring virtual species</a>
</li>
<li>
  <a href="07-sampleoccurrences.html">7. Sampling occurrences</a>
</li>
<li>
  <a href="08-dispersallimitation.html">8. Dispersal limitation</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">6. Exploring virtual species</h1>

</div>


<p>This section is mainly intended to users not very familiar with R.
For example, if you are not sure how to obtain the maps of generated
virtual species, read this section. If you simply want to extract
(sample) occurrence points for your virtual species, then you should
jump to the next section.</p>
<div id="consult-the-details-of-a-generated-virtual-species"
class="section level2">
<h2>6.1. Consult the details of a generated virtual species</h2>
<p>Let’s create a simple virtual species:</p>
<pre class="r"><code>library(virtualspecies)</code></pre>
<pre><code>## Le chargement a nécessité le package : terra</code></pre>
<pre><code>## terra 1.7.46</code></pre>
<pre><code>## The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
## which was just loaded, will retire in October 2023.
## Please refer to R-spatial evolution reports for details, especially
## https://r-spatial.org/r/2023/05/15/evolution4.html.
## It may be desirable to make the sf package available;
## package maintainers should consider adding sf to Suggests:.
## The sp package is now running under evolution status 2
##      (status 2 uses the sf package in place of rgdal)</code></pre>
<pre class="r"><code>library(geodata)
# Worldclim data
worldclim &lt;- worldclim_global(var = &quot;bio&quot;, res = 10,
                              path = tempdir())
names(worldclim) &lt;- paste0(&quot;bio&quot;, 1:19)

# Formatting of the response functions
my.parameters &lt;- formatFunctions(bio1 = c(fun = &#39;dnorm&#39;, mean = 25, sd = 5),
                                 bio12 = c(fun = &#39;dnorm&#39;, mean = 4000, sd = 2000))

# Generation of the virtual species
my.species &lt;- generateSpFromFun(raster.stack = worldclim[[c(&quot;bio1&quot;, &quot;bio12&quot;)]],
                                parameters = my.parameters)</code></pre>
<pre><code>## Generating virtual species environmental suitability...</code></pre>
<pre><code>##  - The response to each variable was rescaled between 0 and 1. To
##             disable, set argument rescale.each.response = FALSE</code></pre>
<pre><code>##  - The final environmental suitability was rescaled between 0 and 1. To disable, set argument rescale = FALSE</code></pre>
<pre class="r"><code># Conversion to presence-absence
my.species &lt;- convertToPA(my.species,
                          beta = 0.7)</code></pre>
<pre><code>##    --- Determing species.prevalence automatically according to alpha and beta</code></pre>
<pre><code>##    Logistic conversion finished:
##               
## - beta = 0.7
## - alpha = -0.05
## - species prevalence =0.024759514536794</code></pre>
<div class="float">
<img src="06-virtualspeciesobjects_files/figure-html/output1-1.png"
alt="Fig. 6.1 Automatic illustration of the randomly generated species" />
<div class="figcaption">Fig. 6.1 Automatic illustration of the randomly
generated species</div>
</div>
<p>If we want to know how it was generated, we simply type the object
name in the R console:</p>
<pre class="r"><code>my.species</code></pre>
<pre><code>## Virtual species generated from 2 variables:
##  bio1, bio12
## 
## - Approach used: Responses to each variable
## - Response functions:
##    .bio1  [min=-54.72435; max=30.98764] : dnorm   (mean=25; sd=5)
##    .bio12  [min=0; max=11191] : dnorm   (mean=4000; sd=2000)
## - Each response function was rescaled between 0 and 1
## - Environmental suitability formula = bio1 * bio12
## - Environmental suitability was rescaled between 0 and 1
## 
## - Converted into presence-absence:
##    .Method = probability
##    .probabilistic method    = logistic
##    .alpha (slope)           = -0.05
##    .beta  (inflexion point) = 0.7
##    .species prevalence      = 0.024759514536794</code></pre>
<p>And a summary of how the virtual species was generated appears:</p>
<ul>
<li>It shows us the variables used.</li>
<li>It shows us the approach used and all the details of the approach,
so we can use it to reconstruct another virtual species with the exact
same parameters later on. It also provides us the range of values of our
environmental variables (bio1 (mean annual temperature) ranged from
-54.72°C to 30.99°C). This is helpful to quickly get an idea of the
preferences of our species; for example here we see that we have a
species living in hot environments, with a peak at 25°C.</li>
<li>If a conversion to presence-absence was performed, it shows us the
parameters of the conversion, and provides the species prevalence (the
species prevalence is always calculated and provided).</li>
<li>If you have introduced a distribution bias (will be seen in a later
section), it will provide information about this particular bias.</li>
</ul>
</div>
<div id="plot-the-virtual-species-map" class="section level2">
<h2>6.2. Plot the virtual species map</h2>
<p>Plotting the distribution maps of a virtual species is
straightforward:</p>
<pre class="r"><code>plot(my.species)</code></pre>
<div class="float">
<img src="06-virtualspeciesobjects_files/figure-html/output3-1.png"
alt="Fig. 6.2 Maps obtained when using the function plot() on virtual species objects" />
<div class="figcaption">Fig. 6.2 Maps obtained when using the function
<code>plot()</code> on virtual species objects</div>
</div>
<p>If the environmental suitability has been converted into
presence-absence, then the plot will conveniently display both the
environmental suitability and the presence-absence map.</p>
</div>
<div id="plot-the-species-environment-relationship"
class="section level2">
<h2>6.3. Plot the species-environment relationship</h2>
<p>As illustrated several times in this tutorial, there is a function to
automatically generate an appropriate plot for your virtual species:
<code>plotResponse</code></p>
<pre class="r"><code>plotResponse(my.species)</code></pre>
<div class="float">
<img src="06-virtualspeciesobjects_files/figure-html/output3bis-1.png"
alt="Fig. 6.3 Example of figure obtained when running plotResponse() on a virtual species object" />
<div class="figcaption">Fig. 6.3 Example of figure obtained when running
<code>plotResponse()</code> on a virtual species object</div>
</div>
</div>
<div
id="plot-the-relationship-between-suitability-and-probability-of-occurrence"
class="section level2">
<h2>6.4. Plot the relationship between suitability and probability of
occurrence</h2>
<p>If you converted your environmental suitability into presence-absence
with a probabilistic approach, chances are that you modified the
environmental suitability function, e.g. if you used a logistic method
or if you wanted to reach a specific prevalence. You may be interested
in the relationship between environmental suitability and probability of
occurrence, which can be plotted with
<code>plotSuitabilityToProba</code></p>
<pre class="r"><code>plotSuitabilityToProba(my.species)</code></pre>
<div class="float">
<img src="06-virtualspeciesobjects_files/figure-html/output3ter-1.png"
alt="Fig. 6.4 Example of figure obtained when running plotSuitabilityToProba() on a virtual species object" />
<div class="figcaption">Fig. 6.4 Example of figure obtained when running
<code>plotSuitabilityToProba()</code> on a virtual species object</div>
</div>
</div>
<div
id="extracting-elements-of-the-virtual-species-such-as-the-rasters-of-environmental-suitability"
class="section level2">
<h2>6.5. Extracting elements of the virtual species, such as the rasters
of environmental suitability</h2>
<p>The virtual species object is structured as a <code>list</code> in R,
which roughly means that it is an object containing many “sub-objects”.
When you run functions on your virtual species object, such as the
conversion into presence-absence, then new sub-objects are added or
replaced in the list.</p>
<p>There is a function allowing you to see the content of the list:
<code>str()</code></p>
<pre class="r"><code>str(my.species)</code></pre>
<pre><code>## List of 6
##  $ approach                 : chr &quot;response&quot;
##  $ details                  :List of 5
##   ..$ variables            : chr [1:2] &quot;bio1&quot; &quot;bio12&quot;
##   ..$ formula              : chr &quot;bio1 * bio12&quot;
##   ..$ rescale.each.response: logi TRUE
##   ..$ rescale              : logi TRUE
##   ..$ parameters           :List of 2
##  $ suitab.raster            :S4 class &#39;SpatRaster&#39; [package &quot;terra&quot;]
##  $ PA.conversion            : Named chr [1:5] &quot;probability&quot; &quot;logistic&quot; &quot;-0.05&quot; &quot;0.7&quot; ...
##   ..- attr(*, &quot;names&quot;)= chr [1:5] &quot;conversion.method&quot; &quot;probabilistic.method&quot; &quot;alpha&quot; &quot;beta&quot; ...
##  $ probability.of.occurrence:S4 class &#39;SpatRaster&#39; [package &quot;terra&quot;]
##  $ pa.raster                :S4 class &#39;SpatRaster&#39; [package &quot;terra&quot;]
##  - attr(*, &quot;class&quot;)= chr [1:2] &quot;virtualspecies&quot; &quot;list&quot;</code></pre>
<p>We are informed that the object is a <code>list</code> containing 5
elements (sub-objects), that you can read on the lines starting with a
<code>$</code>: <code>approach</code>, <code>details</code>,
<code>suitab.raster</code>, <code>PA.conversion</code> and
<code>pa.raster</code>.</p>
<p>You can extract each element using the <code>$</code>: for example,
to extract the suitability raster, type</p>
<pre class="r"><code>my.species$suitab.raster</code></pre>
<pre><code>## class       : SpatRaster 
## dimensions  : 1080, 2160, 1  (nrow, ncol, nlyr)
## resolution  : 0.1666667, 0.1666667  (x, y)
## extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
## coord. ref. : lon/lat WGS 84 (EPSG:4326) 
## source(s)   : memory
## name        : VSP suitability 
## min value   :               0 
## max value   :               1</code></pre>
<p>If you are interested in the probability of occurrence raster,
type</p>
<pre class="r"><code>my.species$probability.of.occurrence</code></pre>
<pre><code>## class       : SpatRaster 
## dimensions  : 1080, 2160, 1  (nrow, ncol, nlyr)
## resolution  : 0.1666667, 0.1666667  (x, y)
## extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
## coord. ref. : lon/lat WGS 84 (EPSG:4326) 
## source(s)   : memory
## name        :        lyr.1 
## min value   : 8.315280e-07 
## max value   : 9.975274e-01</code></pre>
<p>If you are interested in the presence-absence raster, type</p>
<pre class="r"><code>my.species$pa.raster</code></pre>
<pre><code>## class       : SpatRaster 
## dimensions  : 1080, 2160, 1  (nrow, ncol, nlyr)
## resolution  : 0.1666667, 0.1666667  (x, y)
## extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
## coord. ref. : lon/lat WGS 84 (EPSG:4326) 
## source(s)   : memory
## name        : lyr.1 
## min value   :     0 
## max value   :     1</code></pre>
<p><em>Technical note: rasters are terra objects which a stored in a
special format, called ‘wrapped format’, to ensure that these objects
can be safely saved to the disk for reproducibility. When you extract
these rasters from virtualspecies objects with <code>$</code> or
<code>[[ ]]</code>, they are silently unwrapped so that there is no
difference for the users.</em></p>
<p>You can also see that we have “sub-sub-objects”, in the lines
starting with <code>..$</code>: these are objects contained within the
sub-object <code>details</code>. You can also extract them easily:</p>
<pre class="r"><code>my.species$details$variables</code></pre>
<pre><code>## [1] &quot;bio1&quot;  &quot;bio12&quot;</code></pre>
<p>However, the sub-sub-sub-objects (level 3 of depth and beyond) are
not listed when you use <code>str()</code> on the entire virtual species
object. For example, if we extract the <code>parameters</code> object
from the details, we can see that it contains all the function names and
their parameters:</p>
<pre class="r"><code>my.species$details$parameters</code></pre>
<pre><code>## $bio1
## $bio1$fun
##     fun 
## &quot;dnorm&quot; 
## 
## $bio1$args
## mean   sd 
##   25    5 
## 
## $bio1$min
## [1] -54.72435
## 
## $bio1$max
## [1] 30.98764
## 
## 
## $bio12
## $bio12$fun
##     fun 
## &quot;dnorm&quot; 
## 
## $bio12$args
## mean   sd 
## 4000 2000 
## 
## $bio12$min
## [1] 0
## 
## $bio12$max
## [1] 11191</code></pre>
<pre class="r"><code># Looking at how it is structured:
str(my.species$details$parameters)</code></pre>
<pre><code>## List of 2
##  $ bio1 :List of 4
##   ..$ fun : Named chr &quot;dnorm&quot;
##   .. ..- attr(*, &quot;names&quot;)= chr &quot;fun&quot;
##   ..$ args: Named num [1:2] 25 5
##   .. ..- attr(*, &quot;names&quot;)= chr [1:2] &quot;mean&quot; &quot;sd&quot;
##   ..$ min : num -54.7
##   ..$ max : num 31
##  $ bio12:List of 4
##   ..$ fun : Named chr &quot;dnorm&quot;
##   .. ..- attr(*, &quot;names&quot;)= chr &quot;fun&quot;
##   ..$ args: Named num [1:2] 4000 2000
##   .. ..- attr(*, &quot;names&quot;)= chr [1:2] &quot;mean&quot; &quot;sd&quot;
##   ..$ min : num 0
##   ..$ max : num 11191</code></pre>
<p>Hence, the main message here is if you want to explore the content of
the virtual species object, use the function <code>str()</code>, look at
which sub-objects you are interested in, and extract them with
<code>$</code>.</p>
</div>
<div id="saving-the-virtual-species-objects-for-later-use"
class="section level2">
<h2>6.6. Saving the virtual species objects for later use</h2>
<p>If you want to save a virtual species object, you can save it on your
hard drive, using the R function <code>saveRDS()</code>:</p>
<pre class="r"><code>saveRDS(my.species, file = &quot;MyVirtualSpecies.RDS&quot;)</code></pre>
<p>You can load it in a later session of R, using
<code>readRDS()</code>:</p>
<pre class="r"><code>my.species &lt;- readRDS(&quot;MyVirtualSpecies.RDS&quot;)</code></pre>
</div>

<p><br>
<br>
-----------------
<br>


Do not hesitate if you have a question, find a bug, or would like to add a feature in virtualspecies: mail me!</p>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
